services:
  mongo:
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:$27017/
  #     ME_CONFIG_BASICAUTH: false

volumes:
  mongo_data:
    driver: local
